### ISSUE TITLE
Error when launching script

### ISSUE THREAD

**Issue by CyberDing01** [gorgarp/TwitchTranslate#2]
I'm getting this error when running the script:

`(myenv) C:\TwitchTranslate>python transcribe_translate.py es en
Traceback (most recent call last):
  File "C:\TwitchTranslate\transcribe_translate.py", line 9, in <module>
    import whisper
  File "C:\TwitchTranslate\myenv\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ding\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

**Comment by gorgarp** [comment]
Sorry, not sure why it didn't alert me to this when you created it.

Visual C++ Redistributable << install that

**Comment by gorgarp** [comment]
Can you post your actual error?

I *believe* I was using 3.11 at that time, so you may need to use that for a virtual env, at least to confirm.

I know 3.13 broke a few thing on some other code I have, so if you are running that, try 3.11 and report back (or post the exact error message)

**Comment by CyberDing01** [comment]
I tried following everything again with a fresh install of 3.11.9 and I have all the C++ Redistributables installed.

I got this error:

`C:\TwitchTranslate>myenv\Scripts\activate

(myenv) C:\TwitchTranslate>python transcribe_translate.py es en
Traceback (most recent call last):
  File "C:\TwitchTranslate\transcribe_translate.py", line 9, in <module>
    import whisper
  File "C:\TwitchTranslate\myenv\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ding\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

**Comment by gorgarp** [comment]
Hmmm thats very interesting.

Let me test some stuff

**Comment by gorgarp** [comment]
Inside your venv

pip uninstall whisper
pip install openai-whisper

Looks like the whisper library is kind of wonky now

**Comment by gorgarp** [comment]
(I was able to replicate and fix it via that, I updated requirements.txt)

**Comment by CyberDing01** [comment]
Okay, so I got farther and it downloaded a model, but after that, it have me this error now: 

(myenv) C:\TwitchTranslate>python transcribe_translate.py es en
C:\TwitchTranslate\myenv\Lib\site-packages\whisper\__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
error:root:Error loading model Helsinki-NLP/opus-mt-es-en:
MarianTokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.

Traceback (most recent call last):
  File "C:\TwitchTranslate\transcribe_translate.py", line 196, in <module>
    main()
  File "C:\TwitchTranslate\transcribe_translate.py", line 164, in main
    tokenizer, model = load_translation_model(source_lang, target_lang)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TwitchTranslate\transcribe_translate.py", line 63, in load_translation_model
    tokenizer = MarianTokenizer.from_pretrained(model_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TwitchTranslate\myenv\Lib\site-packages\transformers\utils\import_utils.py", line 1690, in __getattribute__
    requires_backends(cls, cls._backends)
  File "C:\TwitchTranslate\myenv\Lib\site-packages\transformers\utils\import_utils.py", line 1678, in requires_backends
    raise ImportError("".join(failed))
ImportError:
MarianTokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation. 

![VA60O2WPp7](https://github.com/user-attachments/assets/0821b597-7ed3-4ced-91bc-4ed3139ff825)

**Comment by CyberDing01** [comment]
AYY, it's working!

**Comment by CyberDing01** [comment]
Ayy, it's working! I just had to install SentencePiece like it said by running this in the environment:

pip install sentencepiece

**Comment by CyberDing01** [comment]
Thanks for the support after all these months!

**Comment by gorgarp** [comment]
NP. I'm sorry I missed these for so long!
